name: 'snowflake_instabee'
version: '1.0.0'
config-version: 2

profile: 'instabee'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  snowflake_instabee:
    staging:
      materialized: view
      snowflake_warehouse: pc_dbt_wh
    marts:
      materialized: table
      snowflake_warehouse: pc_dbt_wh_large
      facts:
        +materialized: table
      dimensions:
        +materialized: table
      transformations:
        +materialized: table

vars:
  surrogate_key_treat_nulls_as_empty_strings: true
