name: dbt build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  dbt-build:
    name: Run dbt build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Configure profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Run dbt build
        run: dbt build
