name: dbt Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.4 dbt-snowflake==1.9.2

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          instabee:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                threads: 4
          EOF
          echo "Profiles.yml content:"
          cat ~/.dbt/profiles.yml

      - name: Setup dbt environment
        run: |
          # Create packages.yml with explicit version
          echo "packages:" > packages.yml
          echo "  - package: dbt-labs/dbt_utils" >> packages.yml
          echo "    version: 1.3.0" >> packages.yml
          
          # Clean environment
          rm -rf ./dbt_packages
          rm -rf ~/.dbt/target

      - name: Run dbt commands
        run: |
          # Install deps and verify
          dbt deps
          echo "dbt_utils macros:"
          ls -la ./dbt_packages/dbt_utils/macros/ || echo "Macros not found"
          
          # Execute with debug
          dbt debug
          dbt build --fail-fast